### PR TITLE
Updated ServiceLayet.Test proj

### PR DESCRIPTION
**Pull request by a-ridley**
Please verify that i updated the UpdateUser() argumenets correctly.

### CODE REVIEW

**Comment by zanderlx** [comment]
The parameters are correct but you also need to pass the values you want to change in the repository (AKA fake DAL)

**Comment by zanderlx** [comment]
The User would not be changed unless you provide the values you want to change to the "Data Access Layer" (repo)

**Comment by a-ridley** [comment]
I fixed the UpdateUser() however, I have a suggestion of breaking the updating into different methods. 
UpdatePassword(), UpdateCity(), UpdateRole()...etc.

**Comment by zanderlx** [comment]
Ok, I will not merge it yet until we discuss it in the meeting. 

Best regards, 

Lex

**Comment by zanderlx** [comment]
Merging pull request. Please standby...

**Pull request merged**
